### ISSUE TITLE
Select - comment about component in styleguide

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#227]
![capture d ecran 2018-08-07 a 15 53 42](https://user-images.githubusercontent.com/33958302/43780110-2399334a-9a5a-11e8-9721-f8b2b07002ab.png)

The "make a choice..." select component looks quite like a Windows 95 dropdown menu.. Could we have it the same style as the "multiple" selection component?

Also, the bottom of the "multiple" selection component doesn't seem to appear when the HTML code box is closed.

**Comment by zufrieden** [comment]
@frizzymagma we use native dropdown from the browser because of : 
- Accessibility
- No need to wait for Javascript to use it
- Resilient web (it will always work)



Multiple selection uses Javascript to handle : 
- Select All
- No need to hold CTRL key to select multiple

The power of using a browser native input is the total responsiveness of it.
![screenshot 2018-08-15 11 48 43](https://user-images.githubusercontent.com/451236/44142691-45e32708-a081-11e8-9ff3-7534511f856d.png)
In this screenshot you see ```select option``` tag going out of the browser window. Something Javascript can't handle ;-)
